###Product Index
GET http://localhost:3000/products/

###Product Show
GET http://localhost:3000/products/3

###Product Create
POST http://localhost:3000/products
Content-Type: application/json

{
 "name": "warm blanket",
 "price": 45,
 "description": "comfortable weighted blanket made for a cozy winter day or night.",
 "image_url": "https://images-us-prod.cms.commerce.dynamics.com/cms/api/cncgmclkfv/imageFileData/search?fileName=/Products%2F136666P%20%5E%20%20%5E%2048X72%20%5E%20Gray%20%5E%20Prime_000_001.png&w=900&h=675&q=80&m=6&f=jpg&cropfocalregion=true"
}

###Product Update
PATCH http://localhost:3000/products/4
Content-Type: application/json 

{
  
}

### Product Destroy
DELETE http://localhost:3000/products/4
Content-Type: application/json 