@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NDgwODkxMjl9.4VzLTvWUcm11thwCkVU6HJat_qNs9G-M7QzCReLC4Eo

###Product Index
GET http://localhost:3000/products/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDc5OTU3MTZ9.F1kYYdZ5Uc2B-4wQW3V5J6vbUQR80Xn2kZHZOwxnE-k
Content-Type: application/json

###Product Show
GET http://localhost:3000/products/3

###Product Create
POST http://localhost:3000/products
Content-Type: application/json

{
 "name": "G.I Joe",
 "price": 30,
 "description": "toy for all ages",
 "image_url": "https://m.media-amazon.com/images/I/81kVhGy0VWL._AC_SY741_.jpg",
 "number_available": 4,
 "supplier_id": 1
}

###Product Update
PATCH http://localhost:3000/products/4
Content-Type: application/json 

{
  
}

### Product Destroy
DELETE http://localhost:3000/products/4
Content-Type: application/json 

### Supplier Index
GET http://localhost:3000/suppliers


### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Bob Young",
  "email": "test1@example.com",
  "password": "password1",
  "password_confirmation": "password1"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test1@example.com",
  "password": "password1"
}

###orders index
GET http://localhost:3000/orders
Authorization: Bearer {{jwt}}

###Orders Create
POST http://localhost:3000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NDgwODM5NDB9.5rFEx9fAN3sKuanVgyS__hm0YHU4AB00qRkkCcniniQ
Content-Type: application/json

{
  "product_id": 2,
  "quantity": 5,
}

###order show
GET http://localhost:3000/orders/1